/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.SubMenusSecundarios.Reservacion;

import com.project.Clases.Reservacion;
import com.project.DAO.ReservacionDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aspxe
 */
public class ActualizarReservacion extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarReservacion
     */
    public ActualizarReservacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdReservacion = new javax.swing.JLabel();
        lblNumeroPersonas = new javax.swing.JLabel();
        txtIdReservacion = new javax.swing.JTextField();
        txtNumeroPersonas = new javax.swing.JTextField();
        lblNumeroNoches = new javax.swing.JLabel();
        txtNumeroNoches = new javax.swing.JTextField();
        lblIdHabitacion = new javax.swing.JLabel();
        txtIdHabitacion = new javax.swing.JTextField();
        lblIdServicio = new javax.swing.JLabel();
        txtIdServicio = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actualizar reservacion");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(450, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(450, 400));

        lblIdReservacion.setText("ID de la reservacion");

        lblNumeroPersonas.setText("Nuevo numero de personas");

        lblNumeroNoches.setText("Nuevo numero de noches");

        lblIdHabitacion.setText("ID de la nueva habitacion");

        lblIdServicio.setText("ID del nuevo servicio");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdReservacion)
                    .addComponent(lblNumeroNoches)
                    .addComponent(lblNumeroPersonas)
                    .addComponent(txtIdReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroNoches, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdHabitacion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtIdServicio, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtIdHabitacion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblIdServicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(btnActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdReservacion)
                    .addComponent(lblIdHabitacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroPersonas)
                    .addComponent(lblIdServicio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblNumeroNoches)
                .addGap(18, 18, 18)
                .addComponent(txtNumeroNoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnActualizar)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int idReservacion = 0, numeroPersonas = 0, numeroNoches = 0, idHabitacion = 0, idServicio = 0;
        
        if(txtIdReservacion.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "ID de la reservacion no ingresado", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            idReservacion = Integer.parseInt(txtIdReservacion.getText());
        }
        if(txtNumeroPersonas.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Nuevo numero de personas no ingresado", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            numeroPersonas = Integer.parseInt(txtNumeroPersonas.getText());
        }
        if(txtNumeroNoches.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Nuevo numero de noches no ingresado", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            numeroNoches = Integer.parseInt(txtNumeroNoches.getText());
        }
        if(txtIdHabitacion.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "ID de la nueva habitacion no ingresado", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            idHabitacion = Integer.parseInt(txtIdHabitacion.getText());
        }
        if(txtIdServicio.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "ID del nuevo servicio no ingresado", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            idServicio = Integer.parseInt(txtIdServicio.getText());
        }
        
        ReservacionDAO rd = new ReservacionDAO();
        Reservacion r = new Reservacion();
        
        r.setFk_habitacionId(idHabitacion);
        r.setFk_serviciosId(idServicio);
        r.setNumeroPersonas(numeroPersonas);
        r.setNumeroNoches(numeroNoches);
        r.setIdReservacion(idReservacion);
        
        try {
            rd.actualizarTodo(r);
            JOptionPane.showMessageDialog(rootPane, "Reservacion actualizada exitosamente", "Registro actualizado", JOptionPane.INFORMATION_MESSAGE);
                    
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarReservacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarReservacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel lblIdHabitacion;
    private javax.swing.JLabel lblIdReservacion;
    private javax.swing.JLabel lblIdServicio;
    private javax.swing.JLabel lblNumeroNoches;
    private javax.swing.JLabel lblNumeroPersonas;
    private javax.swing.JTextField txtIdHabitacion;
    private javax.swing.JTextField txtIdReservacion;
    private javax.swing.JTextField txtIdServicio;
    private javax.swing.JTextField txtNumeroNoches;
    private javax.swing.JTextField txtNumeroPersonas;
    // End of variables declaration//GEN-END:variables
}
