/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.SubMenusPrincipales;

import com.project.SubMenusSecundarios.Habitacion.ActualizarHabitacion;
import com.project.SubMenusSecundarios.Habitacion.EliminarHabitacion;
import com.project.SubMenusSecundarios.Habitacion.IngresarHabitacion;
import com.project.SubMenusSecundarios.Habitacion.VerHabitacion;

/**
 *
 * @author aspxe
 */
public class MenuPrincipalHabitacion extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalHabitacion
     */
    public MenuPrincipalHabitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresarHabitacion = new javax.swing.JButton();
        btnActualizarHabitacion = new javax.swing.JButton();
        btnVerHabitacion = new javax.swing.JButton();
        btnEliminarHabitacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal Habitaciones");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        btnIngresarHabitacion.setText("Ingresar nueva habitacion");
        btnIngresarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarHabitacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarHabitacion);
        btnIngresarHabitacion.setBounds(100, 30, 196, 24);

        btnActualizarHabitacion.setText("Actualizar informacion de una habitacion");
        btnActualizarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHabitacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarHabitacion);
        btnActualizarHabitacion.setBounds(40, 110, 292, 24);

        btnVerHabitacion.setText("Ver lista de habitaciones");
        btnVerHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHabitacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerHabitacion);
        btnVerHabitacion.setBounds(100, 180, 188, 24);

        btnEliminarHabitacion.setText("Eliminar una habitacion");
        btnEliminarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHabitacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarHabitacion);
        btnEliminarHabitacion.setBounds(100, 260, 181, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarHabitacionActionPerformed
        IngresarHabitacion ih = new IngresarHabitacion();
        ih.setVisible(true);
        
    }//GEN-LAST:event_btnIngresarHabitacionActionPerformed

    private void btnActualizarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHabitacionActionPerformed
        ActualizarHabitacion ah = new ActualizarHabitacion();
        ah.setVisible(true);
        
    }//GEN-LAST:event_btnActualizarHabitacionActionPerformed

    private void btnVerHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHabitacionActionPerformed
        VerHabitacion vh = new VerHabitacion();
        vh.setVisible(true);
        
    }//GEN-LAST:event_btnVerHabitacionActionPerformed

    private void btnEliminarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHabitacionActionPerformed
        EliminarHabitacion eh = new EliminarHabitacion();
        eh.setVisible(true);
        
    }//GEN-LAST:event_btnEliminarHabitacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalHabitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarHabitacion;
    private javax.swing.JButton btnEliminarHabitacion;
    private javax.swing.JButton btnIngresarHabitacion;
    private javax.swing.JButton btnVerHabitacion;
    // End of variables declaration//GEN-END:variables
}
