/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.SubMenusPrincipales;

import com.project.SubMenusSecundarios.Reservacion.ActualizarReservacion;
import com.project.SubMenusSecundarios.Reservacion.EliminarReservacion;
import com.project.SubMenusSecundarios.Reservacion.IngresarReservacion;
import com.project.SubMenusSecundarios.Reservacion.VerReservacion;

/**
 *
 * @author aspxe
 */
public class MenuPrincipalReservacion extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalReservacion
     */
    public MenuPrincipalReservacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresarReservacion = new javax.swing.JButton();
        btnActualizarReservacion = new javax.swing.JButton();
        btnVerReservaciones = new javax.swing.JButton();
        btnEliminarReservacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal Reservaciones");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        btnIngresarReservacion.setText("Ingresar una nueva reservacion");
        btnIngresarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarReservacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarReservacion);
        btnIngresarReservacion.setBounds(60, 40, 250, 24);

        btnActualizarReservacion.setText("Actualizar informacion de una reservacion");
        btnActualizarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarReservacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarReservacion);
        btnActualizarReservacion.setBounds(30, 110, 302, 24);

        btnVerReservaciones.setText("Ver lista de reservaciones");
        btnVerReservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReservacionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerReservaciones);
        btnVerReservaciones.setBounds(80, 180, 198, 24);

        btnEliminarReservacion.setText("Eliminar una reservacion");
        btnEliminarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarReservacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarReservacion);
        btnEliminarReservacion.setBounds(90, 250, 191, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarReservacionActionPerformed
        IngresarReservacion ir = new IngresarReservacion();
        ir.setVisible(true);
        
    }//GEN-LAST:event_btnIngresarReservacionActionPerformed

    private void btnActualizarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarReservacionActionPerformed
        ActualizarReservacion ar = new ActualizarReservacion();
        ar.setVisible(true);
        
    }//GEN-LAST:event_btnActualizarReservacionActionPerformed

    private void btnVerReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReservacionesActionPerformed
        VerReservacion vr = new VerReservacion();
        vr.setVisible(true);
        
    }//GEN-LAST:event_btnVerReservacionesActionPerformed

    private void btnEliminarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarReservacionActionPerformed
        EliminarReservacion er = new EliminarReservacion();
        er.setVisible(true);
        
    }//GEN-LAST:event_btnEliminarReservacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalReservacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarReservacion;
    private javax.swing.JButton btnEliminarReservacion;
    private javax.swing.JButton btnIngresarReservacion;
    private javax.swing.JButton btnVerReservaciones;
    // End of variables declaration//GEN-END:variables
}
