/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.SubMenusPrincipales;

import com.project.SubMenusSecundarios.Servicios.ActualizarServicios;
import com.project.SubMenusSecundarios.Servicios.EliminarServicios;
import com.project.SubMenusSecundarios.Servicios.IngresarServicios;
import com.project.SubMenusSecundarios.Servicios.VerServicios;

/**
 *
 * @author aspxe
 */
public class MenuPrincipalServicios extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalServicios
     */
    public MenuPrincipalServicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnIngresarServicio = new javax.swing.JButton();
        btnActualizarServicio = new javax.swing.JButton();
        btnVerServicios = new javax.swing.JButton();
        btnEliminarServicio = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal Servicios");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        btnIngresarServicio.setText("Ingresar un nuevo servicio");
        btnIngresarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarServicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarServicio);
        btnIngresarServicio.setBounds(90, 30, 200, 24);

        btnActualizarServicio.setText("Actualizar informacion de un servicio");
        btnActualizarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarServicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarServicio);
        btnActualizarServicio.setBounds(60, 100, 268, 24);

        btnVerServicios.setText("Ver lista de servicios");
        btnVerServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerServiciosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerServicios);
        btnVerServicios.setBounds(100, 180, 164, 24);

        btnEliminarServicio.setText("Eliminar un servicio");
        btnEliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarServicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarServicio);
        btnEliminarServicio.setBounds(100, 260, 180, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarServicioActionPerformed
        IngresarServicios is = new IngresarServicios();
        is.setVisible(true);
        
    }//GEN-LAST:event_btnIngresarServicioActionPerformed

    private void btnActualizarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarServicioActionPerformed
        ActualizarServicios as = new ActualizarServicios();
        as.setVisible(true);
        
    }//GEN-LAST:event_btnActualizarServicioActionPerformed

    private void btnVerServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerServiciosActionPerformed
        VerServicios vs = new VerServicios();
        vs.setVisible(true);
        
    }//GEN-LAST:event_btnVerServiciosActionPerformed

    private void btnEliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarServicioActionPerformed
        EliminarServicios es = new EliminarServicios();
        es.setVisible(true);
        
    }//GEN-LAST:event_btnEliminarServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarServicio;
    private javax.swing.JButton btnEliminarServicio;
    private javax.swing.JButton btnIngresarServicio;
    private javax.swing.JButton btnVerServicios;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
