/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.SubMenusPrincipales;

import com.project.SubMenusSecundarios.Estacionamiento.ActualizarEstacionamiento;
import com.project.SubMenusSecundarios.Estacionamiento.EliminarEstacionamiento;
import com.project.SubMenusSecundarios.Estacionamiento.IngresarEstacionamiento;
import com.project.SubMenusSecundarios.Estacionamiento.VerEstacionamiento;

/**
 *
 * @author aspxe
 */
public class MenuPrincipalEstacionamiento extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalEstacionamiento
     */
    public MenuPrincipalEstacionamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnIngresarEstacionamiento = new javax.swing.JButton();
        btnActualizarEstacionamiento = new javax.swing.JButton();
        btnVerEstacionamientos = new javax.swing.JButton();
        btnEliminarEstacionamiento = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        btnIngresarEstacionamiento.setText("Ingresar nuevo estacionamiento");
        btnIngresarEstacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarEstacionamientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarEstacionamiento);
        btnIngresarEstacionamiento.setBounds(70, 30, 237, 24);

        btnActualizarEstacionamiento.setText("Actualizar informacion de estacionamiento");
        btnActualizarEstacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEstacionamientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarEstacionamiento);
        btnActualizarEstacionamiento.setBounds(40, 100, 320, 24);

        btnVerEstacionamientos.setText("Ver lista de estacionamientos");
        btnVerEstacionamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstacionamientosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerEstacionamientos);
        btnVerEstacionamientos.setBounds(70, 170, 250, 24);

        btnEliminarEstacionamiento.setText("Eliminar un estacionamiento");
        btnEliminarEstacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstacionamientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarEstacionamiento);
        btnEliminarEstacionamiento.setBounds(70, 250, 260, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarEstacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarEstacionamientoActionPerformed
        IngresarEstacionamiento ie = new IngresarEstacionamiento();
        ie.setVisible(true);
        
    }//GEN-LAST:event_btnIngresarEstacionamientoActionPerformed

    private void btnActualizarEstacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEstacionamientoActionPerformed
        ActualizarEstacionamiento ae = new ActualizarEstacionamiento();
        ae.setVisible(true);
        
    }//GEN-LAST:event_btnActualizarEstacionamientoActionPerformed

    private void btnVerEstacionamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstacionamientosActionPerformed
        VerEstacionamiento ve = new VerEstacionamiento();
        ve.setVisible(true);
        
    }//GEN-LAST:event_btnVerEstacionamientosActionPerformed

    private void btnEliminarEstacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstacionamientoActionPerformed
        EliminarEstacionamiento ee = new EliminarEstacionamiento();
        ee.setVisible(true);
        
    }//GEN-LAST:event_btnEliminarEstacionamientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalEstacionamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEstacionamiento;
    private javax.swing.JButton btnEliminarEstacionamiento;
    private javax.swing.JButton btnIngresarEstacionamiento;
    private javax.swing.JButton btnVerEstacionamientos;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
