/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.SubMenusPrincipales;

import com.project.SubMenusSecundarios.Hotel.ActualizarHotel;
import com.project.SubMenusSecundarios.Hotel.EliminarHotel;
import com.project.SubMenusSecundarios.Hotel.IngresarHotel;
import com.project.SubMenusSecundarios.Hotel.VerHotel;

/**
 *
 * @author aspxe
 */
public class MenuPrincipalHotel extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalHotel
     */
    public MenuPrincipalHotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresarHotel = new javax.swing.JButton();
        btnActualizarHotel = new javax.swing.JButton();
        btnVerHoteles = new javax.swing.JButton();
        btnEliminarHotel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal Hotel");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        btnIngresarHotel.setText("Ingresar nuevo hotel");
        btnIngresarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarHotel);
        btnIngresarHotel.setBounds(80, 40, 210, 24);

        btnActualizarHotel.setText("Actualizar informacion de un hotel");
        btnActualizarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarHotel);
        btnActualizarHotel.setBounds(70, 110, 249, 24);

        btnVerHoteles.setText("Ver lista de hoteles");
        btnVerHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHotelesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerHoteles);
        btnVerHoteles.setBounds(110, 180, 153, 24);

        btnEliminarHotel.setText("Eliminar un hotel");
        btnEliminarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarHotel);
        btnEliminarHotel.setBounds(120, 250, 138, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarHotelActionPerformed
        IngresarHotel ih = new IngresarHotel();
        ih.setVisible(true);
        
    }//GEN-LAST:event_btnIngresarHotelActionPerformed

    private void btnActualizarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHotelActionPerformed
        ActualizarHotel ah = new ActualizarHotel();
        ah.setVisible(true);
        
    }//GEN-LAST:event_btnActualizarHotelActionPerformed

    private void btnVerHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHotelesActionPerformed
        VerHotel vh = new VerHotel();
        vh.setVisible(true);
        
    }//GEN-LAST:event_btnVerHotelesActionPerformed

    private void btnEliminarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHotelActionPerformed
        EliminarHotel eh = new EliminarHotel();
        eh.setVisible(true);
        
    }//GEN-LAST:event_btnEliminarHotelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarHotel;
    private javax.swing.JButton btnEliminarHotel;
    private javax.swing.JButton btnIngresarHotel;
    private javax.swing.JButton btnVerHoteles;
    // End of variables declaration//GEN-END:variables
}
