/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.MenuPrincipal;

import com.project.SubMenusPrincipales.MenuPrincipalAdministradores;
import com.project.SubMenusPrincipales.MenuPrincipalEstacionamiento;
import com.project.SubMenusPrincipales.MenuPrincipalHabitacion;
import com.project.SubMenusPrincipales.MenuPrincipalHotel;
import com.project.SubMenusPrincipales.MenuPrincipalReservacion;
import com.project.SubMenusPrincipales.MenuPrincipalServicios;

/**
 *
 * @author aspxe
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdministradores = new javax.swing.JButton();
        btnEstacionamiento = new javax.swing.JButton();
        btnHotel = new javax.swing.JButton();
        btnHabitacion = new javax.swing.JButton();
        btnReservacion = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal Hotel Tania");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        btnAdministradores.setText("Administradores");
        btnAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministradores);
        btnAdministradores.setBounds(30, 50, 140, 24);

        btnEstacionamiento.setText("Estacionamiento");
        btnEstacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstacionamientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstacionamiento);
        btnEstacionamiento.setBounds(310, 50, 139, 24);

        btnHotel.setText("Hotel");
        btnHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnHotel);
        btnHotel.setBounds(310, 170, 140, 24);

        btnHabitacion.setText("Habitacion");
        btnHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnHabitacion);
        btnHabitacion.setBounds(30, 170, 120, 24);

        btnReservacion.setText("Reservacion");
        btnReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservacion);
        btnReservacion.setBounds(30, 300, 130, 24);

        btnServicios.setText("Servicios");
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        getContentPane().add(btnServicios);
        btnServicios.setBounds(310, 300, 140, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradoresActionPerformed
        MenuPrincipalAdministradores mpa = new MenuPrincipalAdministradores();
        mpa.setVisible(true);
        
    }//GEN-LAST:event_btnAdministradoresActionPerformed

    private void btnEstacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstacionamientoActionPerformed
        MenuPrincipalEstacionamiento mpe = new MenuPrincipalEstacionamiento();
        mpe.setVisible(true);
        
    }//GEN-LAST:event_btnEstacionamientoActionPerformed

    private void btnHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionActionPerformed
        MenuPrincipalHabitacion mph = new MenuPrincipalHabitacion();
        mph.setVisible(true);
        
    }//GEN-LAST:event_btnHabitacionActionPerformed

    private void btnHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelActionPerformed
        MenuPrincipalHotel mpho = new MenuPrincipalHotel();
        mpho.setVisible(true);
        
    }//GEN-LAST:event_btnHotelActionPerformed

    private void btnReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservacionActionPerformed
        MenuPrincipalReservacion mpr = new MenuPrincipalReservacion();
        mpr.setVisible(true);
        
    }//GEN-LAST:event_btnReservacionActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        MenuPrincipalServicios mps = new MenuPrincipalServicios();
        mps.setVisible(true);
        
    }//GEN-LAST:event_btnServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministradores;
    private javax.swing.JButton btnEstacionamiento;
    private javax.swing.JButton btnHabitacion;
    private javax.swing.JButton btnHotel;
    private javax.swing.JButton btnReservacion;
    private javax.swing.JButton btnServicios;
    // End of variables declaration//GEN-END:variables
}
